config/routes.rb
Textmining::Application.routes.draw do
  root to: 'homes#index'
  resources :dummies
  resources :collections  
  resources :contributions
  resources :homes
  resources :challenges
  resources :comments
  resources :users  
  resources :document_term_matrices
  
  match 'term_matrix' => 'document_term_matrices#term_matrix'
  match 'document_matrix' => 'document_term_matrices#document_matrix'
  

end

app/models/dummy.rb
class Dummy < ActiveRecord::Base
	require 'language_processing'
  attr_accessible :description, :document, :dummy_id, :lemma, :title, :user
  include LanguageProcessing
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController
  # GET /dummies
  # GET /dummies.json
  def index
    @dummies = Dummy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dummies }
    end
  end

  # GET /dummies/1
  # GET /dummies/1.json
  def show
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dummy }
    end
  end

  # GET /dummies/new
  # GET /dummies/new.json
  def new
    @dummy = Dummy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dummy }
    end
  end

  # GET /dummies/1/edit
  def edit
    @dummy = Dummy.find(params[:id])
  end

  # POST /dummies
  # POST /dummies.json
  def create
    @dummy = Dummy.new(params[:dummy])

    respond_to do |format|
      if @dummy.save
        format.html { redirect_to @dummy, notice: 'Dummy was successfully created.' }
        format.json { render json: @dummy, status: :created, location: @dummy }
      else
        format.html { render action: "new" }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dummies/1
  # PUT /dummies/1.json
  def update
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      if @dummy.update_attributes(params[:dummy])
        format.html { redirect_to @dummy, notice: 'Dummy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dummy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummies/1
  # DELETE /dummies/1.json
  def destroy
    @dummy = Dummy.find(params[:id])
    @dummy.destroy

    respond_to do |format|
      format.html { redirect_to dummies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/views/dummies/_form.html.haml
= form_for @dummy do |f|
  - if @dummy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dummy.errors.count, "error")} prohibited this dummy from being saved:"
      %ul
        - @dummy.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :dummy_id
    = f.number_field :dummy_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :document
    = f.text_field :document
  .field
    = f.label :lemma
    = f.text_area :lemma
  .actions
    = f.submit 'Save'

app/views/dummies/edit.html.haml
%h1 Editing dummy

= render 'form'

= link_to 'Show', @dummy
\|
= link_to 'Back', dummies_path

app/views/dummies/index.html.haml
%h1 Listing dummies

%table
  %tr
    %th Dummy
    %th Title
    %th Description
    %th User
    %th Document
    %th Lemma
    %th
    %th
    %th

  - @dummies.each do |dummy|
    %tr
      %td= dummy.dummy_id
      %td= dummy.title
      %td= dummy.description
      %td= dummy.user
      %td= dummy.document
      %td= dummy.lemma
      %td= link_to 'Show', dummy
      %td= link_to 'Edit', edit_dummy_path(dummy)
      %td= link_to 'Destroy', dummy, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Dummy', new_dummy_path

app/views/dummies/new.html.haml
%h1 New dummy

= render 'form'

= link_to 'Back', dummies_path

app/views/dummies/show.html.haml
%p#notice= notice

%p
  %b Dummy:
  = @dummy.dummy_id
%p
  %b Title:
  = @dummy.title
%p
  %b Description:
  = @dummy.description
%p
  %b User:
  = @dummy.user
%p
  %b Document:
  = @dummy.document
%p
  %b Lemma:
  = @dummy.lemma

= link_to 'Edit', edit_dummy_path(@dummy)
\|
= link_to 'Back', dummies_path